baseurl = "empowerher.in"
title = "Empower Her"
languageCode = "en-us"
theme = "hugo-elate-theme"


[params]
  
custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = "Empower Her is a small NGO, founded in 2012 in Rishikesh, India to work at grass roots level for and with women living in impoverished slums. It is staffed by a dedicated local team living in the slum areas, whose shared goal is to support and empower disadvantaged women and girls who are disproportionately affected by poverty, lack of education, discrimination, abuse and violations of their rights entitlements, access and control of finances. "
  email = "empowerher.in@gmail.com"

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    logo = "/images/empowerhers.PNG"
    brand = " "
    home = "Home"
    testimonials = "Who We Are"
    work = "What We do"
    services= "Gallery"
    about = "Support"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Empowering Women since 2012."
    subtitle = " "
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = " Our Story"
    description = "We provide adult literacy, handicrafts and computer skills training that enables deprived girls and women from the Rishikesh slum areas that enable income generation to improve quality of life."
    url = "#"
    button = "Get In Touch"
    icon = "icon-book"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Our Mission"
    description = "To alleviate poverty and social exclusion by facilitation empowerment of women and girls from poor and marginalized communities through education and entrepreneurial opportunities."
    url = "#"
    button = "Click Me"
    icon = "icon-target"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Our Vision"
    description = "EmpowerHer seeks the advancement of hope, tolerance and social justice, where poverty has been overcome by fostering sustainable economical development where people live in dignity and security."
    url = "#"
    button = "Why us?"
    icon = "icon-bulb"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://vimeo.com/channels/staffpicks/93951774"


  # Work section is the what we do section
  [params.work]
    enable = true
    title = "What We Do"
    description = "WE SUPPORT GIRLS AND WOMEN TO REACH THEIR FULL POTENTIAL"
  # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    
    [[params.work.row]]
      img = "adult literacy.jpg"
      alt = "adult literacy"
      title = "Adult Literacy"
      subtitle = " "

    [[params.work.row]]
      img = "comp skills.jpg"
      alt = "comp skills"
      title = "Computer Classes"
      subtitle = " "  

    [[params.work.row]]
      img = "handicraft.jpg"
      alt = "handicraft"
      title = "Handicraft training"
      subtitle = " "

   
  # Testimonials section is the donate section
  [params.testimonials]
    enable = true
    title = "Who we are"
    description = " <br> EmpowerHer is an NGO, founded in 2012 in Rishikesh, India working at grass roots for and with women living in impoverished slums. It is staffed by a dedicated local team whose shared goal is to support and empower disadvantaged women and girls who are affected by poverty, lack of education, discrimination, abuse and violations of their rights, entitlements, access and control of finances. Experience has proved that if equipped with proper education and resources, women have the power to help, not only their own families, but whole communities, to overcome poverty, marginalization and social injustice."
    img = "work_14.jpg"

    [[params.testimonials.item]]
      quote = " Dear Friends, <br> EmpowerHer is a registered Non-Governmental Organization, working since 2012 from humble beginnings to improve Women’s rights, gender equality, and education in deprived sections of the local community. EmpowerHer is committed to play an effective role in providing projects designed to implement sustainable, across-the-board improvements. <br>We aim to expand our networks and build robust partnerships to address the issues of poverty, deprivation and exclusion of women through education, health and hygiene awareness and skills training. To achieve these outcomes, we will apply best practices and collaboration with initiatives to create practical strategies towards improved quality of life to which we all aspire.      <br>We need and welcome any help or contribution to develop the scope of our projects: through time, skill sharing, sales of the women beautiful hand made products, donations or fund raising initiatives to empower more girls and women in the communities that we serve. <br> With kind regards, <br> Jatinder Kumar "
      person = 'Jatinder Kumar <span class="subtext"> Founder of Empower Her </span>'
      img = "jatinder.jpg"
      alt = "Jatinder"

  

  # Services section is the gallery
  [params.services]
    enable = true
    title = "Gallery"
    description = " "

    [[params.services.item]]
      img = "1.jpg"
       
    [[params.services.item]]
      img = "2.jpg"  
     
    [[params.services.item]]
      img = "3.jpg"
      
    [[params.services.item]]
      img = "6.jpg"
     
    [[params.services.item]]
      img = "7.jpg"
       
    [[params.services.item]]
      img = "8.jpg"  
     
    [[params.services.item]]
      img = "9.jpg"

    [[params.services.item]]
      img = "10.jpg"
       
    [[params.services.item]]
      img = "11.jpg"  
     
    [[params.services.item]]
      img = "12.jpg"  

    [[params.services.item]]
      img = "4.jpg"
       
    [[params.services.item]]
      img = "5.jpg"  

  # About section
  [params.about]
    enable = true
    title = "Support Us"
    description = " "
    donate1title = "Please donate by bank transfer <br> in the name of “EMPOWER HER” "
    donate1 = "A/C. No: 306902010056812 <br>IFSC Code: UBIN0530697  <br> Bank Name: Union Bank of India <br> Branch: Dehradun Road, Rishikesh, Uttarakhand  "
    donate2title = "You can also donate via PayPal."
    donate2 = " https://www.paypal.me/EmpowerHerIndia "
    info= " Kindly inform us about your contribution along with your contact details, by using our Contact page. <br> This will help us to stay informed about your contribution."

    [[params.about.item]]
      name = "Sponsor a Vocational Trainee"
      position = "You can sponsor the cost of Vocational Training incurred by an underprivileged Slum Artisan with Rs.500 per month per Trainee. This will cover the cost of Training Material, Raw Material, Trainer and the Infrastructure. "
      description = "   "
      img = "trainee.jpg"
      alt = "trainee"
      social = [
        ["icon-paypal", "https://www.paypal.me/EmpowerHerIndia"],
      ]

    [[params.about.item]]
      name = "Sponsor the Cost of a Trainer"
      position = "You can sponsor the cost of a Trainer with Rs.6000 per month and enable the Trainees to learn Livelihood Skills. This will also enable us to deploy guest Trainers for specialized Training Workshops. "
      description = "   "
      img = "trainer.jpg"
      alt = " trainer"
      social = [
        ["icon-bank", ""],
        
      ]      
          
     
  # Counters section
  [params.counters]
    enable = false
    title = "Numbers"
    titles = "Numbers1"
    background = "jarri.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy women"
      icon = "icon-people"
      from = 0
      to = 5600
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Contributions"
      icon = "icon-dollar"
      from = 0
      to = 130200
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy contributors"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "CONTACT US"
    description = "We would love to hear from you!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Chandreshwar Nagar, <br> Dayanand Ashram Road, Street No.5,<br> Near Himalayan Hospital, <br>Rishikesh -249201, Uttarakhand."],
        ["icon-phone", " +91 989 716 9149"],
        ["icon-envelope", "empowerher.in@gmail.com"],
        
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send "

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; All Rights Reserved EmpowerHer'
    links = [
        ["icon-facebook", "https://www.facebook.com/EMPOWERHER.IN/"],
         ["icon-instagram", "https://www.instagram.com/empowerher.in/"],
        ]


     
